{
    "cve_id": "CVE-2023-6597",
    "cve_description": "An issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\n\nThe tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.\n",
    "cve_publish_date": "2024-03-19",
    "cwe_id": "NVD-CWE-noinfo",
    "cwe_name": "Insufficient Information",
    "cwe_description": "There is insufficient information about the issue to classify it; details are unkown or unspecified.",
    "commit_message": "gh-91133: tempfile.TemporaryDirectory: fix symlink bug in cleanup (GH-99930)\n\nCo-authored-by: Serhiy Storchaka <storchaka@gmail.com>",
    "type_of_change": "Modification",
    "filename_of_changes": "test_tempfile.py",
    "code_language": "Python",
    "number_of_lines_added_for_mitigation": "105",
    "number_of_lines_deleted_vulnerable_to_cve": "6",
    "vulnerable_lines": [
        "// Line_Reference 1848:     @unittest.skipUnless(hasattr(os, 'chflags'), 'requires os.chflags')",
        "// Line_Reference 1849:     def test_flags(self):",
        "// Line_Reference 1850:         flags = stat.UF_IMMUTABLE | stat.UF_NOUNLINK",
        "// Line_Reference 1851: ",
        "// Line_Reference 1860:                 self.skipTest(f\"chflags() doesn't support \"",
        "// Line_Reference 1861:                               f\"UF_IMMUTABLE|UF_NOUNLINK: {exc}\")"
    ]
}
