{
    "cve_id": "CVE-2022-23592",
    "cve_description": "Tensorflow is an Open Source Machine Learning Framework. TensorFlow's type inference can cause a heap out of bounds read as the bounds checking is done in a `DCHECK` (which is a no-op during production). An attacker can control the `input_idx` variable such that `ix` would be larger than the number of values in `node_t.args`. The fix will be included in TensorFlow 2.8.0. This is the only affected version.",
    "cve_publish_date": "2022-02-04",
    "cwe_id": "CWE-125",
    "cwe_name": "Out-of-bounds Read",
    "cwe_description": "The product reads data past the end, or before the beginning, of the intended buffer.",
    "commit_message": "Handle invalid inputs instead of crashing.\n\nPiperOrigin-RevId: 409549744\nChange-Id: I7f5935b34b53f7e426a5462fcc027bdbf5dcda24",
    "type_of_change": "Modification",
    "filename_of_changes": "graph.cc",
    "code_language": "C++",
    "number_of_lines_added_for_mitigation": "10",
    "number_of_lines_deleted_vulnerable_to_cve": "4",
    "vulnerable_lines": [
        "// Line_Reference 225:         DCHECK(ix < node_t.args_size())",
        "// Line_Reference 226:             << \"input \" << i << \" should have an output \" << ix",
        "// Line_Reference 227:             << \" but instead only has \" << node_t.args_size()",
        "// Line_Reference 228:             << \" outputs: \" << node_t.DebugString();"
    ]
}
