{
    "cve_id": "CVE-2018-1000807",
    "cve_description": "Python Cryptographic Authority pyopenssl version prior to version 17.5.0 contains a CWE-416: Use After Free vulnerability in X509 object handling that can result in Use after free can lead to possible denial of service or remote code execution.. This attack appear to be exploitable via Depends on the calling application and if it retains a reference to the memory.. This vulnerability appears to have been fixed in 17.5.0.",
    "cve_publish_date": "2018-10-08",
    "cwe_id": "CWE-416",
    "cwe_name": "Use After Free",
    "cwe_description": "The product reuses or references memory after it has been freed. At some point afterward, the memory may be allocated again and saved in another pointer, while the original pointer references a location somewhere within the new allocation. Any operations using the original pointer are no longer valid because the memory \"belongs\" to the code that operates on the new pointer.",
    "commit_message": "fix a memory leak and a potential UAF and also #722 (#723)\n\n* fix a memory leak and a potential UAF and also #722\r\n\r\n* sanity check\r\n\r\n* bump cryptography minimum version, add changelog",
    "type_of_change": "Modification",
    "filename_of_changes": "crypto.py",
    "code_language": "Python",
    "number_of_lines_added_for_mitigation": "3",
    "number_of_lines_deleted_vulnerable_to_cve": "4",
    "vulnerable_lines": [
        "// Line_Reference 3061:         pycert = X509.__new__(X509)",
        "// Line_Reference 3062:         pycert._x509 = _ffi.gc(cert[0], _lib.X509_free)",
        "// Line_Reference 3076:         pycacert = X509.__new__(X509)",
        "// Line_Reference 3077:         pycacert._x509 = _lib.sk_X509_value(cacerts, i)"
    ]
}
