{
    "cve_id": "CVE-2019-19274",
    "cve_description": "typed_ast 1.3.0 and 1.3.1 has a handle_keywordonly_args out-of-bounds read. An attacker with the ability to cause a Python interpreter to parse Python source (but not necessarily execute it) may be able to crash the interpreter process. This could be a concern, for example, in a web-based service that parses (but does not execute) Python code. (This issue also affected certain Python 3.8.0-alpha prereleases.)",
    "cve_publish_date": "2019-11-26",
    "cwe_id": "CWE-125",
    "cwe_name": "Out-of-bounds Read",
    "cwe_description": "The product reads data past the end, or before the beginning, of the intended buffer.",
    "commit_message": "Fix two out-of-bounds array reads (#99)\n\nThe patch is taken from a commit to the CPython repo with the message:\r\n\r\nbpo-36495: Fix two out-of-bounds array reads (GH-12641)\r\n\r\nResearch and fix by @bradlarsen.",
    "type_of_change": "Modification",
    "filename_of_changes": "ast.c",
    "code_language": "C",
    "number_of_lines_added_for_mitigation": "2",
    "number_of_lines_deleted_vulnerable_to_cve": "2",
    "vulnerable_lines": [
        "// Line_Reference 1448:                 if (TYPE(CHILD(n, i)) == COMMA)",
        "// Line_Reference 1647:                 if (TYPE(CHILD(n, i)) == COMMA)"
    ]
}
